#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S3, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     DCMotor1,       sensorI2CMuxController)
#pragma config(Sensor, S3,     DCMotor2,       sensorI2CMuxController)
#pragma config(Sensor, S4,     IRSeeker,       sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     motorA,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Lwheel,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Ltread,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C1_1,     Arm,           tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C1_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_1,     Rwheel,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S3_C2_2,     Rtread,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "drivers/hitechnic-irseeker-v2.h"

/* FUNCTION PROTOTYPES */
void mainAuto();
void zeroEncoder();
void stopRobot();

void initializeRobot()
{
  // Place code here to initialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
}

task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

 	mainAuto(); // Program is fully modular!
}

void mainAuto()
{
	zeroEncoder();
	while(nMotorEncoder[Rwheel] <= 2880) {
		motor[Lwheel] = 70;
		motor[Rwheel] = 70;
	}
	zeroEncoder();
	while(nMotorEncoder[Rwheel] <= 800) {
		motor[Lwheel] = -40;
		motor[Rwheel] = 40;
	}
	zeroEncoder();
	while(nMotorEncoder[Rwheel] <= 2880) {
		motor[Lwheel] = 100;
		motor[Rwheel] = 100;
	}
}

/* REPETITIVE PROCESSES GO HERE */
void zeroEncoder()
{
	nMotorEncoder[Lwheel] = 0;
	nMotorEncoder[Rwheel] = 0;
}

void stopRobot()
{
	motor[Lwheel] = 0;
	motor[Rwheel] = 0;
	motor[Arm] = 0;
	motor[Ltread] = 0;
	motor[Rtread] = 0;
	wait1Msec(20);
}
