#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S3, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     DCMotor1,       sensorI2CMuxController)
#pragma config(Sensor, S2,     IRSeeker,       sensorI2CCustom)
#pragma config(Sensor, S3,     DCMotor2,       sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorA,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Lwheel,        tmotorTetrix, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Ltread,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C1_1,     Arm,           tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C1_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_1,     Rwheel,        tmotorTetrix, reversed, encoder)
#pragma config(Motor,  mtr_S3_C2_2,     Rtread,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		for(int i = 0; i <= 1; ++i) {
			nMotorEncoder[Lwheel] = 0;
			nMotorEncoder[Rwheel] = 0;

			while(nMotorEncoder[Lwheel] <= 7200) {
				motor[Lwheel] = 50;
				motor[Rwheel] = 50;
			}

			nMotorEncoder[Lwheel] = 0;
			nMotorEncoder[Rwheel] = 0;

			while(nMotorEncoder[Lwheel] <= 4320) {
				motor[Lwheel] = 20;
				motor[Rwheel] = -20;
			}
		}

}
